import { delay } from "../utils";

export const getAutoCompleteOptions = async (val) => {
  await delay(500);
  const data = [
    "apple",
    "banana",
    "cherry",
    "dog",
    "elephant",
    "flower",
    "giraffe",
    "happy",
    "ice cream",
    "jazz",
    "kite",
    "lemon",
    "mango",
    "notebook",
    "ocean",
    "penguin",
    "quilt",
    "rainbow",
    "sunshine",
    "tiger",
    "umbrella",
    "violin",
    "watermelon",
    "xylophone",
    "yellow",
    "zebra",
    "awesome",
    "butterfly",
    "cactus",
    "delicious",
    "fantastic",
    "guitar",
    "happiness",
    "internet",
    "jubilant",
    "kiwi",
    "leopard",
    "magnificent",
    "nightingale",
    "orange",
    "pajamas",
    "quasar",
    "rattlesnake",
    "serendipity",
    "tantalizing",
    "unicorn",
    "velvet",
    "whimsical",
    "xylograph",
    "yummy",
    "zeppelin",
    "alligator",
    "bubbles",
    "caramel",
  ];

  return data.filter((d) => d.toLowerCase().indexOf(val.toLowerCase()) > -1);
};
